version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: vsm_go_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - vsm_go_data:/var/lib/postgresql/data

volumes:
  vsm_go_data: